repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-added-large-files

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.12.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.11
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # # Run the formatter.
      #- id: ruff-format

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt # prebuilt upstream executable

  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.3.11" # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.3.10"]

  - repo: https://github.com/PyCQA/bandit
    rev: "1.9.2"
    hooks:
      - id: bandit
        args: ["-c", "bandit.yml"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--config", ".markdown-lint.yml"]

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    # Zizmor version.
    rev: v1.20.0
    hooks:
      # Run the linter.
      - id: zizmor

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.7.4"
    hooks:
      - id: prettier
        types_or: [markdown, yaml, json]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.19.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.39.1" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint

  ## Takes too long
  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: ./backend/venv/bin/pylint
  #       language: system
  #       types: [python]
  #       args: [--ignore-patterns=venv]

  ## Fights with black
  # - repo: https://github.com/hhatto/autopep8
  #   rev: v2.3.2
  #   hooks:
  #     - id: autopep8
